<a href="https://colab.research.google.com/github/Vitalyastiy/NPS/blob/main/Russian%20toxic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
!pip install transformers
!pip install torch
!pip install evaluate

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: transformers in /usr/local/lib/python3.8/dist-packages (4.26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.8/dist-packages (from transformers) (6.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.8/dist-packages (from transformers) (2022.6.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in /usr/local/lib/python3.8/dist-packages (from transformers) (0.12.0)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from transformers) (2.25.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.8/dist-packages (from transformers) (3.9.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/dist-packages (from transformers) (21.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.8/dist-packages (from transformers) (4.64.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.8/dist-packages (from transformers) (0.13.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.8/dist-packages (from transformers) (1.21.6)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.8/dist-packages (from huggingface-hub<1.0,>=0.11.0->transformers) (4.4.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging>=20.0->transformers) (3.0.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests->transformers) (2022.12.7)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->transformers) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests->transformers) (1.26.14)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->transformers) (4.0.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: torch in /usr/local/lib/python3.8/dist-packages (1.13.1+cu116)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.8/dist-packages (from torch) (4.4.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: evaluate in /usr/local/lib/python3.8/dist-packages (0.4.0)
Requirement already satisfied: xxhash in /usr/local/lib/python3.8/dist-packages (from evaluate) (3.2.0)
Requirement already satisfied: dill in /usr/local/lib/python3.8/dist-packages (from evaluate) (0.3.6)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.8/dist-packages (from evaluate) (0.12.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.8/dist-packages (from evaluate) (0.70.14)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from evaluate) (2.8.0)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.8/dist-packages (from evaluate) (2.25.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from evaluate) (21.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.8/dist-packages (from evaluate) (1.21.6)
Requirement already satisfied: responses<0.19 in /usr/local/lib/python3.8/dist-packages (from evaluate) (0.18.0)
Requirement already satisfied: fsspec[http]>=2021.05.0 in /usr/local/lib/python3.8/dist-packages (from evaluate) (2022.11.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from evaluate) (1.3.5)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.8/dist-packages (from evaluate) (4.64.1)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.8/dist-packages (from datasets>=2.0.0->evaluate) (3.8.3)
Requirement already satisfied: pyarrow>=6.0.0 in /usr/local/lib/python3.8/dist-packages (from datasets>=2.0.0->evaluate) (9.0.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.8/dist-packages (from datasets>=2.0.0->evaluate) (6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.8/dist-packages (from huggingface-hub>=0.7.0->evaluate) (3.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.8/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.4.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging->evaluate) (3.0.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->evaluate) (2022.12.7)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->evaluate) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->evaluate) (1.26.14)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->evaluate) (2.10)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas->evaluate) (2022.7)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.1.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.8.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.8/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.3)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.8/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.2)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.8/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.8/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (22.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas->evaluate) (1.15.0)

In [26]:
import pandas as pd
reviews = pd.read_excel('test.xlsx')
df = reviews.dropna()

Подготовим текст:

1.Удалим переносы строк.


2.Оставим только буквенный текст (удалим знаки препинания, цифры и иные символы)


3.Приведём текст к нижнему регистру.

In [ ]:
df.mark_6 = df.mark_6.str.replace('\n', ' ', regex=False)
df.mark_6 = df.mark_6.str.replace('ё', 'е', regex=False)
df.mark_6 = df.mark_6.str.replace('[^a-zA-Zа-яА-Я]+', ' ')
df.mark_6 = df.mark_6.str.lower()

In [29]:
from transformers import pipeline

clf = pipeline(
    task = 'sentiment-analysis', 
    model = 'SkolkovoInstitute/russian_toxicity_classifier')

#text = ['пятигорск']
#clf(text)

In [30]:
def fix_addr(text):
    matches = clf(text)
    return matches #(', '.join(f'{match or ""} {match}' for match in matches)) or None
df['city']=df['mark_6'].map(fix_addr)
df

<ipython-input-30-96210c6cc4c3>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city']=df['mark_6'].map(fix_addr)

,create_date,mark_6,nps,ltr,city
0,2022-12-23,,0,7,"[{'label': 'neutral', 'score': 0.9970947504043..."
5,2023-01-11,г черноголовка ул первая д,0,8,"[{'label': 'neutral', 'score': 0.9996298551559..."
6,2022-12-02,,1,10,"[{'label': 'neutral', 'score': 0.9970947504043..."
14,2022-12-19,у меня тариф вообще дорогой но не хватает мега...,0,7,"[{'label': 'neutral', 'score': 0.9996614456176..."
17,2022-12-16,мариуполь,1,10,"[{'label': 'neutral', 'score': 0.9995848536491..."
...,...,...,...,...,...
18621,2022-12-02,,1,10,"[{'label': 'neutral', 'score': 0.9970947504043..."
18625,2023-01-18,нагинский район поселок воровского,-1,1,"[{'label': 'neutral', 'score': 0.9991944432258..."
18636,2022-12-12,,1,10,"[{'label': 'neutral', 'score': 0.9970947504043..."
18641,2022-12-05,пригородные электропоезда,1,10,"[{'label': 'neutral', 'score': 0.9995182752609..."
18644,2022-12-30,нет,1,10,"[{'label': 'neutral', 'score': 0.9995862841606..."

In [35]:
classifier = pipeline("sentiment-analysis", model="blanchefort/rubert-base-cased-sentiment")

Downloading (…)lve/main/config.json:   0%|          | 0.00/943 [00:00<?, ?B/s]

Downloading (…)"pytorch_model.bin";:   0%|          | 0.00/712M [00:00<?, ?B/s]

Downloading (…)okenizer_config.json:   0%|          | 0.00/499 [00:00<?, ?B/s]

Downloading (…)solve/main/vocab.txt:   0%|          | 0.00/1.40M [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [36]:
def fix_addr(text):
    matches = classifier(text)
    return matches #(', '.join(f'{match or ""} {match}' for match in matches)) or None
df['city']=df['mark_6'].map(fix_addr)
df

<ipython-input-36-cdc11c3fdc56>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city']=df['mark_6'].map(fix_addr)

,create_date,mark_6,nps,ltr,city
0,2022-12-23,,0,7,"[{'label': 'NEUTRAL', 'score': 0.7128436565399..."
5,2023-01-11,г черноголовка ул первая д,0,8,"[{'label': 'NEUTRAL', 'score': 0.8280634284019..."
6,2022-12-02,,1,10,"[{'label': 'NEUTRAL', 'score': 0.7128436565399..."
14,2022-12-19,у меня тариф вообще дорогой но не хватает мега...,0,7,"[{'label': 'NEGATIVE', 'score': 0.751713991165..."
17,2022-12-16,мариуполь,1,10,"[{'label': 'NEUTRAL', 'score': 0.8235167264938..."
...,...,...,...,...,...
18621,2022-12-02,,1,10,"[{'label': 'NEUTRAL', 'score': 0.7128436565399..."
18625,2023-01-18,нагинский район поселок воровского,-1,1,"[{'label': 'NEUTRAL', 'score': 0.8261116147041..."
18636,2022-12-12,,1,10,"[{'label': 'NEUTRAL', 'score': 0.7128436565399..."
18641,2022-12-05,пригородные электропоезда,1,10,"[{'label': 'NEUTRAL', 'score': 0.8269227743148..."
18644,2022-12-30,нет,1,10,"[{'label': 'NEGATIVE', 'score': 0.751659274101..."

In [32]:
classifier = pipeline("sentiment-analysis", model="Tatyana/rubert-base-cased-sentiment-new")

In [33]:
def fix_addr(text):
    matches = classifier(text)
    return matches #(', '.join(f'{match or ""} {match}' for match in matches)) or None
df['city']=df['mark_6'].map(fix_addr)
df

<ipython-input-33-cdc11c3fdc56>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city']=df['mark_6'].map(fix_addr)

,create_date,mark_6,nps,ltr,city
0,2022-12-23,,0,7,"[{'label': 'NEUTRAL', 'score': 0.7128436565399..."
5,2023-01-11,г черноголовка ул первая д,0,8,"[{'label': 'NEUTRAL', 'score': 0.8280634284019..."
6,2022-12-02,,1,10,"[{'label': 'NEUTRAL', 'score': 0.7128436565399..."
14,2022-12-19,у меня тариф вообще дорогой но не хватает мега...,0,7,"[{'label': 'NEGATIVE', 'score': 0.751713991165..."
17,2022-12-16,мариуполь,1,10,"[{'label': 'NEUTRAL', 'score': 0.8235167264938..."
...,...,...,...,...,...
18621,2022-12-02,,1,10,"[{'label': 'NEUTRAL', 'score': 0.7128436565399..."
18625,2023-01-18,нагинский район поселок воровского,-1,1,"[{'label': 'NEUTRAL', 'score': 0.8261116147041..."
18636,2022-12-12,,1,10,"[{'label': 'NEUTRAL', 'score': 0.7128436565399..."
18641,2022-12-05,пригородные электропоезда,1,10,"[{'label': 'NEUTRAL', 'score': 0.8269227743148..."
18644,2022-12-30,нет,1,10,"[{'label': 'NEGATIVE', 'score': 0.751659274101..."

In [37]:
df.to_excel("output.xlsx")