Month

In [1]:
import datetime
import pandas as pd

In [2]:
#Переименовать столбцы
#df = pd.read_csv(r"C:\Users\vitaly.flerin\Desktop\05 Ad hoc\2022-12-01_гео\result_2.csv" , sep=',' , encoding='cp1251', on_bad_lines='skip') #, index_col=0 - индекс 
df= pd.read_excel("NPS + Diss reasons Jan'23.xlsx")
df.columns

Index(['Показатель', 'Оператор', 'Вариант', 'Категория_Выбор', 'Разбивка2',
       'Вариант2', 'Пояснение', 'Jan'22', 'Feb'22', 'Mar'22', 'Apr'22',
       'May'22', 'Jun'22', 'Jul'22', 'Aug'22\n(A)', 'Sep'22\n(B)',
       'Oct'22\n(C)', 'Nov'22\n(D)', 'Dec'22\n(E)', 'Jan'23\n(F)',
       'Base_Jan'23'],
      dtype='object')

In [3]:
df.rename(columns = {"Jan'22": '2022-01-01', "Feb'22":"2022-02-01", "Mar'22":"2022-03-01", "Apr'22":"2022-04-01", "May'22":"2022-05-01", "Jun'22":"2022-06-01", "Jul'22":"2022-07-01", "Aug'22\n(A)":"2022-08-01",\
     "Sep'22\n(B)":"2022-09-01",  "Oct'22\n(C)":"2022-10-01", "Nov'22\n(D)":"2022-11-01", "Dec'22\n(E)":"2022-12-01", "Jan'23\n(F)":"2023-01-01"}, inplace = True)
df.columns

Index(['Показатель', 'Оператор', 'Вариант', 'Категория_Выбор', 'Разбивка2',
       'Вариант2', 'Пояснение', '2022-01-01', '2022-02-01', '2022-03-01',
       '2022-04-01', '2022-05-01', '2022-06-01', '2022-07-01', '2022-08-01',
       '2022-09-01', '2022-10-01', '2022-11-01', '2022-12-01', '2023-01-01',
       'Base_Jan'23'],
      dtype='object')

In [5]:
#Переворачиваем данные(дополнить необходимыми столбцами)
df_unpivot = pd.melt(df, id_vars=['Показатель', 'Оператор', 'Вариант', 'Категория_Выбор', 'Разбивка2', \
       'Вариант2', 'Пояснение',"Base_Jan'23"], value_vars=['2022-01-01', '2022-02-01', '2022-03-01', \
       '2022-04-01', '2022-05-01', '2022-06-01', '2022-07-01', '2022-08-01', '2022-09-01', '2022-10-01', '2022-11-01', '2022-12-01', '2023-01-01'], var_name='Атрибут', value_name='Значение')
df_unpivot

,Показатель,Оператор,Вариант,Категория_Выбор,Разбивка2,Вариант2,Пояснение,Base_Jan'23,Атрибут,Значение
0,Dissatisfied Reasons (NET),МТС,Плохое качество связи,Total Russia all,Subs / nonsubs,Есть МТС,q217a. Что оператор мобильной связи должен улу...,2285,2022-01-01,0.113492
1,Dissatisfied Reasons (NET),МТС,Плохая зона приема/покрытие,Total Russia all,Subs / nonsubs,Есть МТС,q217a. Что оператор мобильной связи должен улу...,2285,2022-01-01,0.286127
2,Dissatisfied Reasons (NET),МТС,"Тарифы (высокие цены, маленький выбор тарифов)",Total Russia all,Subs / nonsubs,Есть МТС,q217a. Что оператор мобильной связи должен улу...,2285,2022-01-01,0.562287
3,Dissatisfied Reasons (NET),МТС,"Роуминг (высокие цены, плохое качество, отсутс...",Total Russia all,Subs / nonsubs,Есть МТС,q217a. Что оператор мобильной связи должен улу...,2285,2022-01-01,0.146660
4,Dissatisfied Reasons (NET),МТС,"Платежи (проблемы с зачислением денег, неудобн...",Total Russia all,Subs / nonsubs,Есть МТС,q217a. Что оператор мобильной связи должен улу...,2285,2022-01-01,0.042063
...,...,...,...,...,...,...,...,...,...,...
1763,NPS,Tele2,NaN,Total Russia all,Subs / nonsubs,Есть Tele2,NPS,3567,2023-01-01,0.244477
1764,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2023-01-01,0.113179
1765,NPS,Билайн,NaN,Moscow,Subs / nonsubs,Есть Билайн,NPS,137,2023-01-01,0.135271
1766,NPS,Мегафон,NaN,Moscow,Subs / nonsubs,Есть Мегафон,NPS,116,2023-01-01,0.251690
1767,NPS,Tele2,NaN,Moscow,Subs / nonsubs,Есть Tele2,NPS,196,2023-01-01,0.332735

In [6]:
print(df_unpivot.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1768 entries, 0 to 1767
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Показатель       1768 non-null   object
 1   Оператор         1768 non-null   object
 2   Вариант          1664 non-null   object
 3   Категория_Выбор  1768 non-null   object
 4   Разбивка2        1768 non-null   object
 5   Вариант2         1768 non-null   object
 6   Пояснение        1768 non-null   object
 7   Base_Jan'23      1768 non-null   int64
 8   Атрибут          1768 non-null   object
 9   Значение         1768 non-null   float64
dtypes: float64(1), int64(1), object(8)
memory usage: 138.2+ KB
None

In [7]:
#Тест
df_unpivot1 = df_unpivot[(df_unpivot['Вариант'].isnull()) & (df_unpivot['Оператор']=="МТС")& (df_unpivot['Категория_Выбор']=="Moscow")]
df_unpivot1

,Показатель,Оператор,Вариант,Категория_Выбор,Разбивка2,Вариант2,Пояснение,Base_Jan'23,Атрибут,Значение
132,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-01-01,0.169664
268,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-02-01,0.007893
404,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-03-01,0.135031
540,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-04-01,0.197689
676,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-05-01,0.280596
812,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-06-01,0.142141
948,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-07-01,0.084678
1084,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-08-01,0.227096
1220,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-09-01,0.145075
1356,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-10-01,0.132833
1492,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-11-01,0.243615
1628,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-12-01,0.178130
1764,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2023-01-01,0.113179

In [9]:
#Тест
decimals = 2
df_unpivot1['value1'] = df_unpivot1['Значение'].apply(lambda x: round(x, decimals))
df_unpivot1

C:\Users\vitaly.flerin\AppData\Local\Temp\ipykernel_8284\3821153162.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unpivot1['value1'] = df_unpivot1['Значение'].apply(lambda x: round(x, decimals))

,Показатель,Оператор,Вариант,Категория_Выбор,Разбивка2,Вариант2,Пояснение,Base_Jan'23,Атрибут,Значение,value1
132,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-01-01,0.169664,0.17
268,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-02-01,0.007893,0.01
404,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-03-01,0.135031,0.14
540,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-04-01,0.197689,0.20
676,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-05-01,0.280596,0.28
812,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-06-01,0.142141,0.14
948,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-07-01,0.084678,0.08
1084,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-08-01,0.227096,0.23
1220,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-09-01,0.145075,0.15
1356,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-10-01,0.132833,0.13
1492,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-11-01,0.243615,0.24
1628,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2022-12-01,0.178130,0.18
1764,NPS,МТС,NaN,Moscow,Subs / nonsubs,Есть МТС,NPS,176,2023-01-01,0.113179,0.11

In [10]:
df_unpivot.to_excel('Январь2023.xlsx', index = False)

Годовой ВИЗ

In [3]:
df = pd.read_excel('Трекинг_Годовые данные NPS_Регионы МР_2021_2022.xlsx')

Index([     'Показатель',        'Оператор',       'Категория',
       'Категория_Выбор',       'Разбивка2',              2021,
            'Unnamed: 6',              2022,       'Base_2021',
             'Base_2022'],
      dtype='object')

In [10]:
df= df[['Показатель', 'Оператор', 'Категория', 'Категория_Выбор', 'Разбивка2', '2021-01-01', '2022-01-01', 'Base_2021', 'Base_2022']]
df.rename(columns={2021:"2021-01-01", 2022:"2022-01-01"}, inplace=True)
df.columns

C:\Users\vitaly.flerin\AppData\Local\Temp\ipykernel_36620\39516394.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={2021:"2021-01-01", 2022:"2022-01-01"}, inplace=True)

Index(['Показатель', 'Оператор', 'Категория', 'Категория_Выбор', 'Разбивка2',
       '2021-01-01', '2022-01-01', 'Base_2021', 'Base_2022'],
      dtype='object')

In [13]:
#переворчиваем нпс
df_unpivot = pd.melt(df, id_vars=['Показатель', 'Оператор', 'Категория', 'Категория_Выбор', 'Разбивка2'], \
    value_vars=['2021-01-01', '2022-01-01'], var_name='year', value_name='NPS')
df_unpivot

,Показатель,Оператор,Категория,Категория_Выбор,Разбивка2,year,NPS
0,NPS,МТС,Macroregion new,Center,Subs / nonsubs,2021-01-01,0.266854
1,NPS,Билайн,Macroregion new,Center,Subs / nonsubs,2021-01-01,0.078107
2,NPS,Мегафон,Macroregion new,Center,Subs / nonsubs,2021-01-01,0.213183
3,NPS,Tele2,Macroregion new,Center,Subs / nonsubs,2021-01-01,0.404435
4,NPS,МТС,Macroregion new,Chernozem,Subs / nonsubs,2021-01-01,0.296571
...,...,...,...,...,...,...,...
663,NPS,Tele2,Region new,Иваново,Subs / nonsubs,2022-01-01,0.526279
664,NPS,МТС,Region new,Ярославль,Subs / nonsubs,2022-01-01,0.133763
665,NPS,Билайн,Region new,Ярославль,Subs / nonsubs,2022-01-01,-0.004017
666,NPS,Мегафон,Region new,Ярославль,Subs / nonsubs,2022-01-01,0.231647
667,NPS,Tele2,Region new,Ярославль,Subs / nonsubs,2022-01-01,0.473353

In [15]:
#переворчиваем базу
df_unpivot_b = pd.melt(df, id_vars=['Показатель', 'Оператор', 'Категория', 'Категория_Выбор', 'Разбивка2'], \
    value_vars=['Base_2021', 'Base_2022'], var_name='year_cnt', value_name='subs')
df_unpivot_b

,Показатель,Оператор,Категория,Категория_Выбор,Разбивка2,year_cnt,subs
0,NPS,МТС,Macroregion new,Center,Subs / nonsubs,Base_2021,7601
1,NPS,Билайн,Macroregion new,Center,Subs / nonsubs,Base_2021,5682
2,NPS,Мегафон,Macroregion new,Center,Subs / nonsubs,Base_2021,4645
3,NPS,Tele2,Macroregion new,Center,Subs / nonsubs,Base_2021,7126
4,NPS,МТС,Macroregion new,Chernozem,Subs / nonsubs,Base_2021,6448
...,...,...,...,...,...,...,...
663,NPS,Tele2,Region new,Иваново,Subs / nonsubs,Base_2022,750
664,NPS,МТС,Region new,Ярославль,Subs / nonsubs,Base_2022,801
665,NPS,Билайн,Region new,Ярославль,Subs / nonsubs,Base_2022,840
666,NPS,Мегафон,Region new,Ярославль,Subs / nonsubs,Base_2022,517
667,NPS,Tele2,Region new,Ярославль,Subs / nonsubs,Base_2022,752

In [16]:
#merge
df_full=pd.merge(df_unpivot , df_unpivot_b[['year_cnt', 'subs']], left_index= True, right_index=True, how='left') # 'on =' - для джойна по столбцу
df_full

,Показатель,Оператор,Категория,Категория_Выбор,Разбивка2,year,NPS,year_cnt,subs
0,NPS,МТС,Macroregion new,Center,Subs / nonsubs,2021-01-01,0.266854,Base_2021,7601
1,NPS,Билайн,Macroregion new,Center,Subs / nonsubs,2021-01-01,0.078107,Base_2021,5682
2,NPS,Мегафон,Macroregion new,Center,Subs / nonsubs,2021-01-01,0.213183,Base_2021,4645
3,NPS,Tele2,Macroregion new,Center,Subs / nonsubs,2021-01-01,0.404435,Base_2021,7126
4,NPS,МТС,Macroregion new,Chernozem,Subs / nonsubs,2021-01-01,0.296571,Base_2021,6448
...,...,...,...,...,...,...,...,...,...
663,NPS,Tele2,Region new,Иваново,Subs / nonsubs,2022-01-01,0.526279,Base_2022,750
664,NPS,МТС,Region new,Ярославль,Subs / nonsubs,2022-01-01,0.133763,Base_2022,801
665,NPS,Билайн,Region new,Ярославль,Subs / nonsubs,2022-01-01,-0.004017,Base_2022,840
666,NPS,Мегафон,Region new,Ярославль,Subs / nonsubs,2022-01-01,0.231647,Base_2022,517
667,NPS,Tele2,Region new,Ярославль,Subs / nonsubs,2022-01-01,0.473353,Base_2022,752

In [17]:
df_full['year']= pd.to_datetime( df_full['year'])

In [18]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 668 entries, 0 to 667
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Показатель       668 non-null    object
 1   Оператор         668 non-null    object
 2   Категория        668 non-null    object
 3   Категория_Выбор  668 non-null    object
 4   Разбивка2        668 non-null    object
 5   year             668 non-null    datetime64[ns]
 6   NPS              668 non-null    float64
 7   year_cnt         668 non-null    object
 8   subs             668 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(6)
memory usage: 47.1+ KB

In [19]:
df_full.to_excel('итог-2021-2022.xlsx')